name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: "build the app"
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: "tests"
        run: pnpm run test:run

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: "lint"
        run: pnpm run lint
      

